src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 * @ORM\Table(name="product", indexes={@ORM\Index(columns={"titre", "refernce"}, flags={"fulltext"})})
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $refernce;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $in_stock = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="product")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Media::class, mappedBy="product")
     */
    private $media;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_enregistrement;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="productsproducts")
     */
    private $user;

    public function __construct()
    {
        $this->media = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getRefernce(): ?string
    {
        return $this->refernce;
    }

    public function setRefernce(?string $refernce): self
    {
        $this->refernce = $refernce;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getInStock(): ?array
    {
        return $this->in_stock;
    }

    public function setInStock(?array $in_stock): self
    {
        $this->in_stock = $in_stock;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|Media[]
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media[] = $medium;
            $medium->setProduct($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getProduct() === $this) {
                $medium->setProduct(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->titre;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(?\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }


}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\FileType;


class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('refernce')
            ->add('prix')
            ->add('description')
            ->add('in_stock')
            ->add('quantity')
            ->add('categorie')
            ->add('media', FileType::class, [
                "multiple" => true,
                "mapped" => false,
                "required" => false,

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\Media;
use App\Form\ProductType;
use App\Controller\BasketController;

use App\Form\CategorieType;

use App\Data\SearchData;
use App\Form\SearchForm;

use App\Repository\ProductRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



#[Route('/product')]
class ProductController extends AbstractController
{
    #[Route('/', name: 'product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository, Request $request): Response
    {
        $data = new SearchData();
        $data->page = $request->get('page', 1);
        $form = $this->createForm(SearchForm::class, $data);
        $form->handleRequest($request);
        $products = $productRepository->findSearch($data);
        return $this->render('product/index.html.twig', [
            // 'products' => $productRepository->findAll(),
            'products'=> $products,
            'form'=> $form->createView()
        ]);
    }

    #[Route('/new', name: 'product_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $product->setDateEnregistrement(new \DateTimeImmutable('now'));
            $user=$this->getUser();
            $product->setUser($user);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();

            $mediaFile = $form->get('media')->getData();

            if($mediaFile){
                for ($i=0; $i < count($mediaFile); $i++){
                    $media = new Media;

                    $nomMedia = date("TmdHis") . "-" . uniqid() . "-" . $mediaFile[$i]->getClientOriginalName();

                    $mediaFile[$i]->move(
                        $this->getParameter("media_product"),
                        $nomMedia
                    );

                    $media->setNom($nomMedia);
                    $media->setProduct($product);
                    $type = ["image"];
                    $media->setType($type);

                    $entityManager->persist($media);
                    $entityManager->flush();
                }
            }
            // $this->addFlash("success", "L'annonce n°  a bien été ajoutée");

            return $this->redirectToRoute('product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('product/new.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'product_show', methods: ['GET'])]
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    #[Route('/{id}/edit', name: 'product_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'product_delete', methods: ['POST'])]
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('product_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/product/111index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
    <h1>Product index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Refernce</th>
                <th>Prix</th>
                <th>Description</th>
                <th>In_stock</th>
                <th>Quantity</th>
                <th>Pictures</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.titre }}</td>
                <td>{{ product.refernce }}</td>
                <td>{{ product.prix }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.inStock ? product.inStock|json_encode : '' }}</td>
                <td>{{ product.quantity }}</td>
                <td>{% for media in product.media %}
                    <img src="{{ asset("media/mediaUpload/" ~ media.nom ) }}" alt="" style="width:200px">

                {% endfor %}</td>
                <td>
                    <a href="{{ path('product_show', {'id': product.id}) }}">show</a>
                    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('product_new') }}">Create new</a>
{% endblock %}

templates/product/_card.html.twig
<div class="card">
    {% for media in product.media %}
        <img src="{{ asset("media/mediaUpload/" ~ media.nom ) }}" alt="" style="width:200px" class="card-img-top">
    {% endfor %}
    <div class="card-body">
        <h3 class="card=title">{{ product.titre }}</h3>
        <h6 class="card=title">{{ product.refernce }}</h6>
        <div class="card-title" style="font-weight: bold; font-size: 1.5rem;">
        {{ product.prix | number_format(0, ',',' ')}} €
        </div>
        <p class="text text-muted">{{ product.description }}</p>
        <a href="{{ path('product_show', {'id': product.id}) }}">show</a>
        <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>
        <div>
            {% for c in product.categorie %}
                <em class="text-muted text-primary text-italic">#{{ c.nom }}</em>
            {% endfor %}
        </div>
        <div>
            <a href="{{ path('add_to_basket', {id: product.id})}}" class="btn btn-success">
            <i class="bi bi-cart-plus"></i> Ajouter
            </a>
        </div>
    </div>
    
</div>

<style>
	.grid {
		display: grid;
		grid-template-columns: repeat(3, 1fr);
		grid-gap: 20px
	}
</style>

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product/_filter.html.twig
{{ form_start(form, {attr: {class: 'filter js-filter-form'}}) }}
<div class="spinner-border js-loading" role="status" aria-hidden="true" style="display: none">
	<span class="sr-only">Loading...</span>
</div>

    {{ form_row(form.q) }}
    <h4>Catégorie</h4>
    {{ form_row(form.categories) }}

    <h4>Prix</h4>
    <div class="row">
        <div class="col-md-6">
            {{ form_row(form.min) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.max)}}
        </div>
    </div>
    <div id="price-slider"></div>
{# data-min="{{ min }}" data-max="{{ max }}  style="margin-bottom: 3rem" #}



<button type="submit" class="btn btn-primary w-100">Filter</button>

{{ form_end(form) }}

templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product/catalogue.html.twig
{% block body %}

    {% if products %}

    {% include 'product/_filter.html.twig' with {form: form} only %}


        <div class="row justify-content-around">

            {% for product in products %}

                <div class="col-md-3 col-sm-5 cardCatalogue p-3 m-4 text-center">
                
                    <h5>{{ product.titre|capitalize }}</h5>

                    {% for media in product.media %}
                        <img src="{{ asset("media/mediaUpload/" ~ media.nom ) }}" alt="" style="width:150px"> 
                    
                    {% endfor %}

                    <h5>{{ product.prix }} €</h5>

                     <a class="btn btn-danger col-md-12" href="{{     path(  'product_show'  ,    {'id' : product.id }    )       }}">Voir la fiche</a> 

                </div>
                
            {% endfor %}

        </div>
    {% else %}
        <h4 class="text-center text-danger mt-3 fst-italic">Il n'y a aucun produit pour le moment</h4>
    {% endif %}




{% endblock %}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Tous nos Produis{% endblock %}



{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				{% include 'product/_filter.html.twig' with {form: form} only %}
			</div>

			<div class="col-md-9">
				<div class="grid">
					{% for product in products %}
						{% include 'product/_card.html.twig'  with {product: product} only %}
					{% endfor %}
				</div>
				<div style="mt-4">
					{{ knp_pagination_render(products) }}
				</div>

			</div>
		</div>	
			
	</div>
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('product_index') }}">back to list</a>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ product.titre }}</td>
            </tr>
            <tr>
                <th>Refernce</th>
                <td>{{ product.refernce }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ product.prix }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ product.description }}</td>
            </tr>
            <tr>
                <th>In_stock</th>
                <td>{{ product.inStock ? product.inStock|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ product.quantity }}</td>
            </tr>
        </tbody>
    </table>

            <div class="col-md-4 mt-5">
            <div class="row">
                {% for media in product.media %}
                    <img src="{{ asset("media/mediaUpload/" ~ media.nom ) }}" alt="" style="width:200px">

                {% endfor %}
            </div>
        </div>

    <a href="{{ path('product_index') }}">back to list</a>

    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>

<div>
	<a href="{{ path('add_to_basket', {id: product.id})}}" class="btn btn-success">
		<i class="bi bi-cart-plus"></i>
		Ajouter
	</a>
</div>


    {{ include('product/_delete_form.html.twig') }}
{% endblock %}